export const romania: Record<string, string[]> = {
  Alba: ["Alba Iulia", "Aiud", "Blaj", "Sebeș"],
  Arad: ["Arad", "Ineu", "Lipova"],
  Argeș: ["Pitești", "Curtea de Argeș", "Câmpulung"],
  Bacău: ["Bacău", "Onești"],
  Bihor: ["Oradea", "Salonta"],
  "Bistrița-Năsăud": ["Bistrița"],
  Botoșani: ["Botoșani"],
  Brașov: ["Brașov", "Făgăraș"],
  Brăila: ["Brăila"],
  București: ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6"],
  Buzău: ["Buzău"],
  Caraș: ["Reșița"],
  Cluj: ["Cluj-Napoca", "Turda", "Dej", "Gherla"],
  Constanța: ["Constanța", "Mangalia"],
  Covasna: ["Sfântu Gheorghe"],
  Dâmbovița: ["Târgoviște"],
  Dolj: ["Craiova"],
  Galați: ["Galați"],
  Giurgiu: ["Giurgiu"],
  Gorj: ["Târgu Jiu"],
  Harghita: ["Miercurea Ciuc"],
  Hunedoara: ["Deva", "Hunedoara"],
  Ialomița: ["Slobozia"],
  Iași: ["Iași", "Pașcani"],
  Ilfov: ["Voluntari"],
  Maramureș: ["Baia Mare"],
  Mehedinți: ["Drobeta"],
  Mureș: ["Târgu Mureș"],
  Neamț: ["Piatra Neamț"],
  Olt: ["Slatina", "Caracal"],
  Prahova: ["Ploiești", "Câmpina"],
  "Satu Mare": ["Satu Mare", "Carei"], // 🔥 FIX
  Sălaj: ["Zalău"],
  Sibiu: ["Sibiu", "Mediaș"],
  Suceava: ["Suceava", "Fălticeni"],
  Teleorman: ["Alexandria"],
  Timiș: ["Timișoara", "Lugoj"],
  Tulcea: ["Tulcea"],
  Vaslui: ["Vaslui", "Bârlad"],
  Vâlcea: ["Râmnicu Vâlcea"],
  Vrancea: ["Focșani"],
};